name: react-graphql-recruitment-task
services:
  react-graphql-recruitment-task:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: react-graphql-recruitment-task
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
